import { NextResponse } from "next/server"
import type { Employee } from "@/lib/types/employee"

const mockEmployees: Employee[] = [
  {
    id: "1",
    name: "Brooklyn Simmons",
    avatar: "/professional-woman-diverse.png",
    email: "brooklyn.simmons@betopia.com",
    phone: "+1 (555) 123-4567",
    employeeId: "124335111",
    department: "PM",
    designation: "Project Manager",
    type: "Office",
    status: "Permanent",
    joinDate: "2023-01-15",
    salary: 85000,
  },
  {
    id: "2",
    name: "Darlene Robertson",
    avatar: "/professional-woman-designer.png",
    email: "darlene.robertson@betopia.com",
    phone: "+1 (555) 234-5678",
    employeeId: "345321231",
    department: "Design",
    designation: "UI/UX Designer",
    type: "Office",
    status: "Permanent",
    joinDate: "2023-02-20",
    salary: 75000,
  },
  {
    id: "3",
    name: "Floyd Miles",
    avatar: "/professional-man-developer.png",
    email: "floyd.miles@betopia.com",
    phone: "+1 (555) 345-6789",
    employeeId: "987890345",
    department: "Development",
    designation: "PHP Developer",
    type: "Office",
    status: "Permanent",
    joinDate: "2023-03-10",
    salary: 80000,
  },
  {
    id: "4",
    name: "Cody Fisher",
    avatar: "/professional-man-sales.png",
    email: "cody.fisher@betopia.com",
    phone: "+1 (555) 456-7890",
    employeeId: "453367122",
    department: "Sales",
    designation: "Sales Manager",
    type: "Office",
    status: "Permanent",
    joinDate: "2023-04-05",
    salary: 90000,
  },
  {
    id: "5",
    name: "Dianne Russell",
    avatar: "/professional-woman-sales.png",
    email: "dianne.russell@betopia.com",
    phone: "+1 (555) 567-8901",
    employeeId: "345321231",
    department: "Sales",
    designation: "BDM",
    type: "Remote",
    status: "Permanent",
    joinDate: "2023-05-12",
    salary: 70000,
  },
  {
    id: "6",
    name: "Savannah Nguyen",
    avatar: "/professional-woman-design-lead.png",
    email: "savannah.nguyen@betopia.com",
    phone: "+1 (555) 678-9012",
    employeeId: "453677881",
    department: "Design",
    designation: "Design Lead",
    type: "Office",
    status: "Permanent",
    joinDate: "2023-06-18",
    salary: 95000,
  },
  {
    id: "7",
    name: "Jacob Jones",
    avatar: "/professional-man-python-developer.png",
    email: "jacob.jones@betopia.com",
    phone: "+1 (555) 789-0123",
    employeeId: "009918765",
    department: "Development",
    designation: "Python Developer",
    type: "Remote",
    status: "Permanent",
    joinDate: "2023-07-22",
    salary: 85000,
  },
  {
    id: "8",
    name: "Marvin McKinney",
    avatar: "/professional-man-senior-developer.png",
    email: "marvin.mckinney@betopia.com",
    phone: "+1 (555) 890-1234",
    employeeId: "238870122",
    department: "Development",
    designation: "Sr. UI Developer",
    type: "Remote",
    status: "Permanent",
    joinDate: "2023-08-30",
    salary: 100000,
  },
  {
    id: "9",
    name: "Kristin Watson",
    avatar: "/professional-woman-hr-executive.png",
    email: "kristin.watson@betopia.com",
    phone: "+1 (555) 901-2345",
    employeeId: "435540099",
    department: "HR",
    designation: "HR Executive",
    type: "Office",
    status: "Permanent",
    joinDate: "2023-09-15",
    salary: 65000,
  },
  {
    id: "10",
    name: "Kathryn Murphy",
    avatar: "/professional-woman-react-developer.png",
    email: "kathryn.murphy@betopia.com",
    phone: "+1 (555) 012-3456",
    employeeId: "009812890",
    department: "Development",
    designation: "React JS Developer",
    type: "Office",
    status: "Permanent",
    joinDate: "2023-10-08",
    salary: 78000,
  },
]

export async function GET() {
  await new Promise((resolve) => setTimeout(resolve, 500))

  return NextResponse.json(mockEmployees)
}
